insert into products (name, price) values ('Anthracinum,', 7587.01);
insert into products (name, price) values ('Oxygen', 7475.55);
insert into products (name, price) values ('OCTINOXATE, OCTOCRYLENE, OCTISALATE, and OXYBENZONE', 8707.54);
insert into products (name, price) values ('Povidone-Iodine', 1085.75);
insert into products (name, price) values ('OXYBENZONE, AVOBENZONE, OCTOCRYLENE', 5064.84);
insert into products (name, price) values ('Octinoxate and Oxybenzone', 1508.77);
insert into products (name, price) values ('Donepezil Hydrochloride', 1799.08);
insert into products (name, price) values ('Calcipotriene', 8922.93);
insert into products (name, price) values ('Yellow Jacket hymenoptera venom Venomil Maintenance', 4137.24);
insert into products (name, price) values ('amlodipine besylate', 6550.38);
insert into products (name, price) values ('OYSTER SHELL CALCIUM CARBONATE, CRUDE - GOLDENSEAL - POTASSIUM DICHROMATE', 3110.81);
insert into products (name, price) values ('Temozolomide', 9807.91);
insert into products (name, price) values ('Nystatin', 9306.22);
insert into products (name, price) values ('MINERAL OIL', 7661.35);
insert into products (name, price) values ('Selenium Sulfide', 873.02);
insert into products (name, price) values ('Diphenhydramine HCl', 1340.66);
insert into products (name, price) values ('Aluminum Zirconium Trichlorohydrex Gly', 9854.05);
insert into products (name, price) values ('Prednisone', 5703.52);
insert into products (name, price) values ('Octinoxate and Oxybenzone', 8636.13);
insert into products (name, price) values ('Titanium Dioxide', 4925.96);
insert into products (name, price) values ('clobetasol propionate', 7984.16);
insert into products (name, price) values ('erythromycin', 4150.72);
insert into products (name, price) values ('Lidocaine Hydrochloride and Hydrocortisone Acetate', 3743.76);
insert into products (name, price) values ('Prednisone', 5909.2);
insert into products (name, price) values ('NyQuil Cherry', 6780.95);
insert into products (name, price) values ('Etodolac', 8288.85);
insert into products (name, price) values ('Pravastatin Sodium', 1277.74);
insert into products (name, price) values ('Glycerin', 2015.86);
insert into products (name, price) values ('amlodipine besylate and atorvastatin calcium', 6415.31);
insert into products (name, price) values ('ALUMINUM CHLOROHYDRATE', 7276.24);
insert into products (name, price) values ('Tetracycline Hydrochloride', 1919.01);
insert into products (name, price) values ('amlodipine besylate and atorvastatin calcium', 4642.21);
insert into products (name, price) values ('BENZOYL PEROXIDE', 2788.21);
insert into products (name, price) values ('benazepril hydrochloride and hydrochlorothiazide', 8726.44);
insert into products (name, price) values ('Rash Prevention Cream', 2258.8);
insert into products (name, price) values ('LIDOCAINE HYDROCHLORIDE', 8456.06);
insert into products (name, price) values ('ALUMINUM SESQUICHLOROHYDRATE', 8174.75);
insert into products (name, price) values ('VENLAFAXINE HYDROCHLORIDE', 8695.02);
insert into products (name, price) values ('Ibuprofen', 1142.75);
insert into products (name, price) values ('OCTINOXATE, OCTISALATE, OXYBENZONE, and TITANIUM DIOXIDE', 4405.45);
insert into products (name, price) values ('aluminum hydroxide, magnesium hydroxide, dimethicone', 2303.37);
insert into products (name, price) values ('Panthenol (0.2%), Biotin (0.06%)', 7412.95);
insert into products (name, price) values ('Beta vulgaris, Carduus marianus, Lappa major, Aluminium metallicum, Arsenicum album, Chelidonium majus, Hydrastis canadensis, Lycopodium clavatum, Natrum sulphuricum, Nux vomica, Phosphorus,', 129.17);
insert into products (name, price) values ('Gabapentin', 4790.68);
insert into products (name, price) values ('Doxycycline hyclate', 274.48);
insert into products (name, price) values ('BRYONIA ALBA', 2182.06);
insert into products (name, price) values ('divalproex sodium', 6373.73);
insert into products (name, price) values ('Ketoconazole', 7947.2);
insert into products (name, price) values ('Cefazolin', 1176.44);
insert into products (name, price) values ('Prednisone', 9567.24);
insert into products (name, price) values ('Fentanyl buccal', 1753.4);
insert into products (name, price) values ('Loperamide Hydrochloride', 9870.34);
insert into products (name, price) values ('Saccharomyces cerevisiae', 4888.48);
insert into products (name, price) values ('Lambs Quarters', 8626.85);
insert into products (name, price) values ('Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', 8065.32);
insert into products (name, price) values ('Octinoxate and Oxybenzone', 4783.16);
insert into products (name, price) values ('MERCURIUS SOLUBILIS', 9765.23);
insert into products (name, price) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 9043.65);
insert into products (name, price) values ('Torsemide', 1849.66);
insert into products (name, price) values ('Benzethonium chloride', 1078.16);
insert into products (name, price) values ('nicotine', 5796.62);
insert into products (name, price) values ('ciprofloxacin hydrochloride', 1687.87);
insert into products (name, price) values ('Zinc oxide', 129.37);
insert into products (name, price) values ('Metoprolol succinate', 6634.53);
insert into products (name, price) values ('Ondansetron', 6775.98);
insert into products (name, price) values ('Prednisone', 4146.6);
insert into products (name, price) values ('Animal Allergens, Dog Dander Canis spp', 4335.71);
insert into products (name, price) values ('Atropa Belladonna, Arnica Montana', 9362.29);
insert into products (name, price) values ('Chloroxylenol', 1659.62);
insert into products (name, price) values ('Ethyl Alcohol', 8362.16);
insert into products (name, price) values ('Agnus C. 30c, Borax 30c, Condurango 30c, Graphites 30c, Iodium 30c, Medorrhinum 30c, Nat Mur 30c, Platina 30c', 3294.53);
insert into products (name, price) values ('DIEFFENBACHIA SEGUINE, DAPHNE ODORA BARK, GRAPHITES, VALERIAN', 2790.45);
insert into products (name, price) values ('isotretinoin', 7544.77);
insert into products (name, price) values ('egg', 1672.37);
insert into products (name, price) values ('Ropinirole', 1696.34);
insert into products (name, price) values ('Docusate sodium and Sennosides', 3705.66);
insert into products (name, price) values ('Acetaminophen, Doxylamine succinate and Phenylephrine Hydrochloride', 257.57);
insert into products (name, price) values ('secobarbital sodium', 409.76);
insert into products (name, price) values ('Amoxicillin and Clavulanate Potassium', 5946.23);
insert into products (name, price) values ('Titanium Dioxide', 2609.97);
insert into products (name, price) values ('CLOVE', 4445.38);
insert into products (name, price) values ('Pravastain Sodium', 3336.52);
insert into products (name, price) values ('fexofenadine hydrochloride', 2136.41);
insert into products (name, price) values ('Famotidine', 6386.15);
insert into products (name, price) values ('Menthol', 9683.0);
insert into products (name, price) values ('TRICLOSAN', 866.4);
insert into products (name, price) values ('Ciprofloxacin', 3196.61);
insert into products (name, price) values ('Betaxolol', 1339.0);
insert into products (name, price) values ('Treatment Set TS347628', 7127.83);
insert into products (name, price) values ('perampanel', 5676.48);
insert into products (name, price) values ('Polyethylene Glycol 3350', 4363.5);
insert into products (name, price) values ('ZINC OXIDE', 8066.37);
insert into products (name, price) values ('benzonatate', 8477.02);
insert into products (name, price) values ('SIMETHICONE', 8621.34);
insert into products (name, price) values ('SODIUM CHLORIDE', 8386.4);
insert into products (name, price) values ('Antihemophilic Factor (Recombinant)', 4008.23);
insert into products (name, price) values ('Acyclovir', 7562.33);
insert into products (name, price) values ('ERIODICTYON CALIFORNICUM, IPECACUANHA, LOBELIA INFLATA, CHAMOMILLA, BELLADONNA, COFFEA CRUDA, SOLIDAGO VIRGAUREA, SAMBUCUS NIGRA, CRATAEGUS', 5474.96);
insert into products (name, price) values ('Melatonin, Nadidum, Niacin, Pyridoxinum hydrochloricum, Zincum sulphuricum, Hypothalamus, Lithium carbonicum, Magnesia carbonica, Pineal, Pituitary,', 3254.98);
insert into products (name, price) values ('Chlorpheniramine Maleate', 3629.83);
insert into products (name, price) values ('Anticoagulant Citrate Phosphate Dextrose (CPD) Solution and ADSOL Preservation Solution', 5309.39);
insert into products (name, price) values ('topiramate', 5839.35);
insert into products (name, price) values ('Benzoyl Peroxide', 6041.67);
insert into products (name, price) values ('Fosinopril Sodium and Hydrochlorothiazide', 7484.11);
insert into products (name, price) values ('HUMAN RABIES VIRUS IMMUNE GLOBULIN', 3631.35);
insert into products (name, price) values ('hydrocortisone acetate and pramoxine hydrochloride', 9444.93);
insert into products (name, price) values ('potassium chloride', 7780.12);
insert into products (name, price) values ('Acetaminophen, Dextromethorphan HBr, Doxylamine succinate, Phenylephrine HCl', 587.45);
insert into products (name, price) values ('dalteparin sodium', 4247.9);
insert into products (name, price) values ('ZINC OXIDE, OCTINOXATE', 1781.23);
insert into products (name, price) values ('Brompheniramine maleate, Phenylephrine HCl', 2947.95);
insert into products (name, price) values ('Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 8646.04);
insert into products (name, price) values ('secobarbital sodium', 9184.25);
insert into products (name, price) values ('PETROLATUM', 1962.12);
insert into products (name, price) values ('Meclizine Hydrochloride', 3480.35);
insert into products (name, price) values ('OCTINOXATE and TITANIUM DIOXIDE', 6731.25);
insert into products (name, price) values ('ITRACONAZOLE', 4710.83);
insert into products (name, price) values ('Diltiazem Hydrochloride', 1684.69);
insert into products (name, price) values ('ARIPIPRAZOLE', 7718.51);
insert into products (name, price) values ('Codeine Phosphate, Pseudoephedrine Hydrochloride, Brompheniramine Maleate', 5962.65);
insert into products (name, price) values ('ACREMONIUM STRICTUM', 6081.52);
insert into products (name, price) values ('Olanzapine', 5446.48);
insert into products (name, price) values ('Glipizide', 6615.54);
insert into products (name, price) values ('Montelukast Sodium', 5358.25);
insert into products (name, price) values ('Octinoxate and Oxybenzone', 2958.44);
insert into products (name, price) values ('ACETAMINOPHEN, PHENYLEPHRINE HCL, DEXTROMETHORPHAN HBr', 2838.91);
insert into products (name, price) values ('acetaminophen, dextromethorphan hydrobromide and doxylamine succinate', 5191.99);
insert into products (name, price) values ('Potassium Iodide', 2932.2);
insert into products (name, price) values ('Lorazepam', 1039.3);
insert into products (name, price) values ('telmisartan', 1937.61);
insert into products (name, price) values ('Hydrogen peroxide', 5583.98);
insert into products (name, price) values ('Acetaminophen, Diphenhydramine HCl', 5514.38);
insert into products (name, price) values ('isopropyl alcohol', 4328.66);
insert into products (name, price) values ('Titanium Dioxide, OCTINOXATE, Zinc Oxide', 6138.99);
insert into products (name, price) values ('Titanium dioxide', 2566.14);
insert into products (name, price) values ('sildenafil citrate', 7502.9);
insert into products (name, price) values ('conium maculatum flowering top, sodium chloride, ruta graveolens flowering top and polygala senega root', 3303.85);
insert into products (name, price) values ('WITCH HAZEL', 1571.53);
insert into products (name, price) values ('TITANIUM DIOXIDE', 2200.46);
insert into products (name, price) values ('Labetalol Hydrochloride', 4225.77);
insert into products (name, price) values ('Zinc Oxide', 2765.99);
insert into products (name, price) values ('BENZOYL PEROXIDE', 984.99);
insert into products (name, price) values ('Avobenzone, Homosalate, Octisalate, and Octocrylene', 5826.12);
insert into products (name, price) values ('Ziprasidone Hydrochloride Monohydrate', 4808.72);
insert into products (name, price) values ('Titanium Dioxide and Zinc Oxide', 3573.78);
insert into products (name, price) values ('Indomethacin', 7443.13);
insert into products (name, price) values ('Anticavity Fluoride', 9536.6);
insert into products (name, price) values ('Amoxicillin', 1028.79);
insert into products (name, price) values ('Miconazole Nitrate', 994.79);
insert into products (name, price) values ('amlodipine besylate and atorvastatin calcium', 7929.4);
insert into products (name, price) values ('ingredients', 523.58);
insert into products (name, price) values ('ARNICA MONTANA', 3749.02);
insert into products (name, price) values ('Oxytocin', 3710.12);
insert into products (name, price) values ('Hydroquinone', 1413.56);
insert into products (name, price) values ('Nitrous Oxide', 7328.5);
insert into products (name, price) values ('Rho(D) Immune Globulin (Human)', 8275.88);
insert into products (name, price) values ('Octinoxate and Oxybenzone', 631.6);
insert into products (name, price) values ('methylphenidate hydrochloride', 8081.51);
insert into products (name, price) values ('Diclofenac Sodium', 4607.68);
insert into products (name, price) values ('Chlorpheniramine maleate, Phenylephrine HCl', 5497.38);
insert into products (name, price) values ('Rabbitbush', 8269.5);
insert into products (name, price) values ('Oxygen', 3463.42);
insert into products (name, price) values ('Octinoxate', 5998.01);
insert into products (name, price) values ('Labetalol Hydrochloride', 716.75);
insert into products (name, price) values ('Quinapril Hydrochloride and Hydrochlorothiazide', 918.64);
insert into products (name, price) values ('Desvenlafaxine', 7562.55);
insert into products (name, price) values ('OXYGEN, CARBON DIOXIDE', 1931.22);
insert into products (name, price) values ('MIDODRINE HYDROCHLORIDE', 322.1);
insert into products (name, price) values ('ISOMETHEPTENE MUCATE, DICHLORALPHENAZONE, and ACETAMINOPHEN', 4288.52);
insert into products (name, price) values ('lamotrigine', 1972.72);
insert into products (name, price) values ('Salicylic Acid', 5219.56);
insert into products (name, price) values ('Wheat Smut', 7337.82);
insert into products (name, price) values ('Hydrocortisone', 4304.15);
insert into products (name, price) values ('TITANIUM DIOXIDE', 7504.36);
insert into products (name, price) values ('OCTINOXATE OXYBENZONE', 6973.37);
insert into products (name, price) values ('Pseudoephedrine Hydrochloride', 3480.61);
insert into products (name, price) values ('Glandula Thymus 4', 3163.91);
insert into products (name, price) values ('DICYCLOMINE HYDROCHLORIDE', 8756.54);
insert into products (name, price) values ('PETROLATUM', 1774.25);
insert into products (name, price) values ('lansoprazole', 5299.98);
insert into products (name, price) values ('Titanium Dioxide', 443.36);
insert into products (name, price) values ('ZINC OXIDE', 4298.1);
insert into products (name, price) values ('ALPRAZOLAM', 2787.22);
insert into products (name, price) values ('Tretinoin', 557.94);
insert into products (name, price) values ('Lamotrigine', 1473.25);
insert into products (name, price) values ('Phenytoin', 1690.2);
insert into products (name, price) values ('hydrogen peroxide', 9846.14);
insert into products (name, price) values ('Clonidine Hydrochloride', 7529.76);
insert into products (name, price) values ('Zaleplon', 7181.17);
insert into products (name, price) values ('Octinoxate and Titanium Dioxide', 1067.73);
insert into products (name, price) values ('AVOBENZONE, OCTINOXATE, OCTOCRYLENE', 5685.1);
insert into products (name, price) values ('hydroxyzine hydrochloride', 8965.67);
insert into products (name, price) values ('Cetirizine Hydrochloride', 1197.58);
insert into products (name, price) values ('Silicea Belladonna', 8487.21);
insert into products (name, price) values ('Escitalopram', 8627.01);
insert into products (name, price) values ('buprenorphine hydrochloride, naloxone hydrochloride', 7830.58);
insert into products (name, price) values ('Hydrogen Peroxide', 3923.68);
insert into products (name, price) values ('SENNOSIDES', 971.25);
insert into products (name, price) values ('Glycopyrrolate', 3187.87);
insert into products (name, price) values ('Sodium Fluoride', 1394.08);
