insert into shops (name, city, address) values ('Linklinks', 'Muḩambal', '723 Victoria Way');
insert into shops (name, city, address) values ('Mycat', 'Kladanj', '506 Kedzie Terrace');
insert into shops (name, city, address) values ('Feedfish', 'Nozdrzec', '33093 Luster Lane');
insert into shops (name, city, address) values ('Dynabox', 'Stockholm', '849 Wayridge Plaza');
insert into shops (name, city, address) values ('Ntag', 'Hufang', '2 Mendota Alley');
insert into shops (name, city, address) values ('Lazz', 'Camacha', '7069 Holy Cross Street');
insert into shops (name, city, address) values ('Edgeclub', 'Lewotola', '23861 Westend Street');
insert into shops (name, city, address) values ('Dablist', 'Miami', '6236 Lakewood Crossing');
insert into shops (name, city, address) values ('Jamia', 'Dazhan', '39 Sycamore Court');
insert into shops (name, city, address) values ('Geba', 'Vide', '64845 Tennessee Crossing');
insert into shops (name, city, address) values ('Quire', 'Palilula', '8159 Warner Crossing');
insert into shops (name, city, address) values ('Zoozzy', 'Senhor da Serra', '38441 Vidon Crossing');
insert into shops (name, city, address) values ('Yakidoo', 'Salima', '75263 Dexter Hill');
insert into shops (name, city, address) values ('Dabvine', 'Okinawa', '8913 Saint Paul Alley');
insert into shops (name, city, address) values ('Topiclounge', 'Konobeyevo', '0 Gerald Park');
insert into shops (name, city, address) values ('Riffpath', 'Alto de la Estancia', '14116 Stang Trail');
insert into shops (name, city, address) values ('Quinu', 'Jianggu', '23 Green Ridge Pass');
insert into shops (name, city, address) values ('Feedfire', 'Divnoye', '36 Shelley Terrace');
insert into shops (name, city, address) values ('Zooxo', 'Xinchenglu', '5097 Russell Road');
insert into shops (name, city, address) values ('Gabvine', 'Huashan', '192 Morning Junction');
insert into shops (name, city, address) values ('Devpulse', 'Bolyarovo', '67849 Maple Alley');
insert into shops (name, city, address) values ('Yotz', 'Xingang', '44624 Hagan Place');
insert into shops (name, city, address) values ('Dazzlesphere', 'Mê Linh', '817 Prairie Rose Center');
insert into shops (name, city, address) values ('Browseblab', 'Cikeusal', '3 Magdeline Lane');
insert into shops (name, city, address) values ('Meembee', 'Jiguan', '35336 Stoughton Crossing');
insert into shops (name, city, address) values ('Blogpad', 'Diapaga', '122 Jackson Junction');
insert into shops (name, city, address) values ('JumpXS', 'Jangheung', '35 Derek Junction');
insert into shops (name, city, address) values ('Devpulse', 'Cicayur', '80016 Bartelt Pass');
insert into shops (name, city, address) values ('Roomm', 'Shanghu', '9741 Pleasure Place');
insert into shops (name, city, address) values ('Dabtype', 'Huangli', '50124 Forster Park');
insert into shops (name, city, address) values ('Zooveo', 'Gouping', '92 Grover Terrace');
insert into shops (name, city, address) values ('Gabcube', 'Progreso', '063 Towne Terrace');
insert into shops (name, city, address) values ('Kwideo', 'Staffanstorp', '045 Pearson Place');
insert into shops (name, city, address) values ('Katz', 'Lagoa do Itaenga', '7 Loomis Place');
insert into shops (name, city, address) values ('Skinix', 'Sukawaris', '53778 Emmet Alley');
insert into shops (name, city, address) values ('Agimba', 'Gbadolite', '48 Veith Parkway');
insert into shops (name, city, address) values ('Plajo', 'Mamer', '3 Helena Trail');
insert into shops (name, city, address) values ('Roombo', 'Santa Ana', '1963 Sunnyside Road');
insert into shops (name, city, address) values ('Zoovu', 'Lewoluo', '7 Evergreen Crossing');
insert into shops (name, city, address) values ('Divanoodle', 'Gunungjulang', '0 Monterey Place');
insert into shops (name, city, address) values ('Eidel', 'Murcia', '354 Nobel Court');
insert into shops (name, city, address) values ('Jatri', 'Songkar B', '9389 Beilfuss Avenue');
insert into shops (name, city, address) values ('Oyonder', 'Šardice', '9795 Forest Run Parkway');
insert into shops (name, city, address) values ('Eidel', 'Mananum', '96465 Harper Point');
insert into shops (name, city, address) values ('Oyoba', 'Campamento', '3044 Lindbergh Junction');
insert into shops (name, city, address) values ('Nlounge', 'Ilha de Moçambique', '2 Northfield Circle');
insert into shops (name, city, address) values ('Wikizz', 'Prakhon Chai', '5921 Talisman Park');
insert into shops (name, city, address) values ('Photolist', 'Mandeni', '6 Lindbergh Circle');
insert into shops (name, city, address) values ('Shufflebeat', 'Clermont-Ferrand', '169 Debra Road');
insert into shops (name, city, address) values ('Skibox', 'Swift Current', '04063 Coleman Hill');
